// Generates src/poker/preflopRanking.ts: all 169 starting hands ordered by
// heads-up all-in equity against a random hand. Run with: node scripts/rankPreflop.ts
import { writeFileSync } from 'node:fs';
import { evaluate } from '../src/poker/evaluator.ts';
import { HAND_CLASSES, combosOfClass } from '../src/poker/handClasses.ts';

const TRIALS = 30000;

function equityVsRandom(hero: [number, number]): number {
  const deck = Array.from({ length: 52 }, (_, i) => i).filter((c) => !hero.includes(c));
  let total = 0;
  for (let t = 0; t < TRIALS; t++) {
    // Partial Fisher-Yates for 7 cards: 2 villain + 5 board.
    for (let i = 0; i < 7; i++) {
      const j = i + Math.floor(Math.random() * (deck.length - i));
      [deck[i], deck[j]] = [deck[j], deck[i]];
    }
    const board = deck.slice(2, 7);
    const h = evaluate([hero[0], hero[1], ...board]);
    const v = evaluate([deck[0], deck[1], ...board]);
    total += h > v ? 1 : h === v ? 0.5 : 0;
  }
  return total / TRIALS;
}

const ranked = HAND_CLASSES.map((cls) => ({
  label: cls.label,
  equity: equityVsRandom(combosOfClass(cls)[0]),
})).sort((a, b) => b.equity - a.equity);

const body = ranked.map((r) => `  ['${r.label}', ${r.equity.toFixed(4)}],`).join('\n');
writeFileSync(
  new URL('../src/poker/preflopRanking.ts', import.meta.url),
  `// Generated by scripts/rankPreflop.ts. Starting hands ordered by heads-up
// equity against a random hand (best first).
export const PREFLOP_RANKING: [label: string, equity: number][] = [
${body}
];
`,
);
console.log(ranked.slice(0, 10), ranked.slice(-5));
